title: Prepa
description: > # Descripción más larga que puede abarcar varias líneas.
  Este es un sitio de ejemplo para mostrar cómo aplicar un tema de Jekyll.
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you have one
